spring:
  security:
    user:
      name: ${SECURITY_USER_NAME:admin}
      password: ${SECURITY_USER_PASSWORD:adminpassword}
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: todoapp
      auto-index-creation: true
